
--DROP TABLE IF EXISTS user;
--DROP TABLE IF EXISTS texts;
--
--CREATE TABLE user (
--  id INTEGER PRIMARY KEY AUTOINCREMENT,
--  email TEXT UNIQUE NOT NULL,
--  password TEXT NOT NULL
--);
--
--CREATE TABLE texts (
--  old_text TEXT NOT NULL,
--  new_text TEXT NOT NULL
--);